name: Bindings

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: true

    name: Check bindings are up to date
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install go1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Add Ethereum PPA
        run: sudo add-apt-repository -y ppa:ethereum/ethereum

      - name: Install Abigen
        run: sudo apt-get update && sudo apt-get install ethereum

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v0.3.0

      - name: Generate new bindings
        run: make bindings

      - name: Compare bindings
        run: git diff --exit-code
