name: check bindings are up-to-date
on:
  push:
    branches:
      - dev
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  make-bindings:
    name: make bindings and check for diffs
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install go1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install abigen
        run: go install github.com/ethereum/go-ethereum/cmd/abigen@latest

      - name: run make bindings and check for diffs
        run: |
          make bindings
          # sudo required due to bindings being owned by root
          if [ ! -z "$(sudo git status --porcelain)" ]; then
            printf "Current generated bindings not up to date\n"
            sudo git diff
            sudo git status
            exit 1
          fi
