name: generate anvil state
on:
  push:
    branches:
      - dev
  pull_request:
  merge_group:

jobs:
  generate-anvil-state:
    name: generate anvil state
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Generate anvil state
        run: make deploy-contracts-to-anvil-and-save-state
